/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IProfileArgs } from "./Components/Interfaces/Compositions/web-card/web-card.model";
export namespace Components {
    interface WebAvatar {
        "avatar": string;
    }
    interface WebCard {
        "backgroundCover": string;
        "icon": string;
        "profileArgs": IProfileArgs;
    }
    interface WebHeader {
        "igniteSimbol": string;
    }
    interface WebUserProfile {
        "coverThumbnail": string;
        "direction": 'row' | 'column';
        "name": string;
        "occupation": string;
    }
}
export interface WebCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWebCardElement;
}
declare global {
    interface HTMLWebAvatarElement extends Components.WebAvatar, HTMLStencilElement {
    }
    var HTMLWebAvatarElement: {
        prototype: HTMLWebAvatarElement;
        new (): HTMLWebAvatarElement;
    };
    interface HTMLWebCardElement extends Components.WebCard, HTMLStencilElement {
    }
    var HTMLWebCardElement: {
        prototype: HTMLWebCardElement;
        new (): HTMLWebCardElement;
    };
    interface HTMLWebHeaderElement extends Components.WebHeader, HTMLStencilElement {
    }
    var HTMLWebHeaderElement: {
        prototype: HTMLWebHeaderElement;
        new (): HTMLWebHeaderElement;
    };
    interface HTMLWebUserProfileElement extends Components.WebUserProfile, HTMLStencilElement {
    }
    var HTMLWebUserProfileElement: {
        prototype: HTMLWebUserProfileElement;
        new (): HTMLWebUserProfileElement;
    };
    interface HTMLElementTagNameMap {
        "web-avatar": HTMLWebAvatarElement;
        "web-card": HTMLWebCardElement;
        "web-header": HTMLWebHeaderElement;
        "web-user-profile": HTMLWebUserProfileElement;
    }
}
declare namespace LocalJSX {
    interface WebAvatar {
        "avatar"?: string;
    }
    interface WebCard {
        "backgroundCover"?: string;
        "icon"?: string;
        "onEditUserPerfilClicked"?: (event: WebCardCustomEvent<any>) => void;
        "profileArgs"?: IProfileArgs;
    }
    interface WebHeader {
        "igniteSimbol"?: string;
    }
    interface WebUserProfile {
        "coverThumbnail"?: string;
        "direction"?: 'row' | 'column';
        "name"?: string;
        "occupation"?: string;
    }
    interface IntrinsicElements {
        "web-avatar": WebAvatar;
        "web-card": WebCard;
        "web-header": WebHeader;
        "web-user-profile": WebUserProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "web-avatar": LocalJSX.WebAvatar & JSXBase.HTMLAttributes<HTMLWebAvatarElement>;
            "web-card": LocalJSX.WebCard & JSXBase.HTMLAttributes<HTMLWebCardElement>;
            "web-header": LocalJSX.WebHeader & JSXBase.HTMLAttributes<HTMLWebHeaderElement>;
            "web-user-profile": LocalJSX.WebUserProfile & JSXBase.HTMLAttributes<HTMLWebUserProfileElement>;
        }
    }
}
